name: build

# Controls when the action will run. Triggers the workflow on push or pull request events
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #    strategy:
    #      matrix:
    #        os: [ubuntu-latest, macos-latest]
    #    runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dotfiles
      run: |
        rm ~/.bash_profile ~/.bashrc  # due to file existing in github actions
        bash install
